### ISSUE TITLE
[Tracking] Homogenize to existing bevy animation capability

### ISSUE THREAD

**Issue by KirmesBude** [KirmesBude/bevy_trickfilm#1]
The crate is currently designed based on how animations are handled in other engines and whatever I needed. 
It probably makes sense to design this as close as possible to what bevy already offers. 

- [x] The Assets should be something close to AnimationClip
- [x] AnimationPlayer should offer roughly the same functions
- [x] AnimationClips need to be cleaned up a bit so nobody can construct empty AnimationClips
- [x] AnimationClips should hold KeyframeTimestamps and KeyframeIndices
- [x] Add example using sprites instead of spritesheet
